# Generated by Django 4.2 on 2023-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('date_of_creation', models.DateTimeField(verbose_name='date of creation')),
                ('date_of_expiry', models.DateTimeField(verbose_name='date of expiry')),
                ('category', models.CharField(choices=[('Math', 'Math'), ('Biology', 'Biology'), ('Chemi', 'Chemi')], max_length=20, verbose_name='category')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
            ],
        ),
    ]
