# Generated by Django 4.2 on 2023-07-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='execute',
            field=models.PositiveIntegerField(default=0, verbose_name='execute'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
